### ISSUE TITLE
%f and %F cannot be used together in the same printf statement.

### ISSUE THREAD

**Issue by rzinsly** [libdfp/libdfp#1]
Printf statements that uses %f and %Hf  didn't work, the values printed will be zero instead of the real values of the variables in %f and %Hf.

For example, this: printf("%f (long double) %Hf (_Decimal64)\n", number, dd)
Will generate this output: 0.000000 (long double) 0.000000 (_Decimal64)

From libdfp side, for a value with 32 bits the function __d32_va (./printf_dfp.c:300) is called with the wrong parameter va_list *ap when this combination occurs, so the function stores the wrong value (something like 0E-101), maybe this is caused by some bug in glibc side.

When %f and %Hf is used together ___printf_fp is called earlier in _IO_vfprintf_internal than other hook combinations that I observed, maybe this could indicate what is wrong.

**Comment by tuliom** [comment]
As explained in pull request #8 , we can't reproduce this issue anymore.
