### ISSUE TITLE
Integrate libbid from GCC

### ISSUE THREAD

**Issue by pmur** [libdfp/libdfp#117]
GCC has a copy of libbid and also an FSF project under the same license. We should also provide a copy to ensure this library is reasonably performant on BID targets (e.g x86) too.

Such should also remove the mini-gmp implementation, and copy the work done in GCC to convert between decNumber and BID formats.

**Comment by segher** [comment]
If changes in GCC are needed as well, timing isn't great, it might miss GCC-10.1?

**Comment by pmur** [comment]
A did a first pass against this. Only minor changes were required to support PLT bypasses and wrangle exception flags. I'm not sure what, if any, the GCC community might be interested in.

**Comment by kenpocowboy** [comment]
This is great news !  Thank you !

My immediate concern is Linux on X.
Next up is AIX (where I use the system libdecNumber)
Then will be Linux on P.
Finally, if I am still around, Linux on Z.

Having one, common, library will make my life *so* much easier :-)

I will give master some testing

**Comment by pmur** [comment]
And integrated now.
