### ISSUE TITLE
Regression on ppc and ppc64

### ISSUE THREAD

**Issue by tuliom** [libdfp/libdfp#129]
I've been seeing the following failure on ppc and ppc64 since commit ad9746cb86c91a8cafed20951cadfaf1543f04d8:

```
cat ./check-localplt.out 
Extra PLT reference: libdfp.so: __dpd_gedd2
FAIL: check-localplt
Summary of test results:
      1 FAIL
    160 PASS
```

**Comment by pmur** [comment]
soft-dfp I assume?

**Comment by tuliom** [comment]
@pmur Correct.  For both cases.

**Comment by pmur** [comment]
Confirmed. The move of expd64 into common code exposed this.  This redirect is missing from `sysdeps/dpd/symbol-hacks.h`

**Comment by stliibm** [comment]
Just as information:
I've just tested this on s390x/s390 without hardware dfp. Then I'm also seeing this issue.

**Comment by stliibm** [comment]
Thanks. I've retested this on s390x/s390 without hardware dfp. There are no fails anymore.
