### ISSUE TITLE
Investigate quantize() results

### ISSUE THREAD

**Issue by tuliom** [libdfp/libdfp#14]
The following output has been reported by an user.
It looks like quantize() is giving better results than the test expects.
Reproduced on power8.

Output:
6../test-quantize-d32
...
Test: quantize (-0.1, 1.0)
Result:
 is:         -1.00000000000000000000e-01  -1.00000000e-01
 should be:  -0.00000000000000000000e+00  -0.00000000e+00
 difference:  1.00000000000000000000e-01  1.00000000e-01
 ulp       : -0.0000
 max.ulp   :  0.0000

7../test-quantize-d64
...
Test: quantize (-0.1, 1.0)
Result:
 is:         -1.00000000000000000000e-01 -1.0000000000000000e-01
 should be:  -0.00000000000000000000e+00 -0.0000000000000000e+00
 difference:  1.00000000000000000000e-01 1.0000000000000000e-01
 ulp       : -0.0000
 max.ulp   :  0.0000
...

8../test-quantize-d128
...
Test: quantize (-0.1, 1.0)
Result:
 is:         -1.00000000000000000000e-01
-1.0000000000000000000000000000000000e-01
 should be:  -0.00000000000000000000e+00
-0.0000000000000000000000000000000000e+00
 difference: -1.00000000000000000000e-01
-1.0000000000000000000000000000000000e-01
 ulp       :  0.0000
 max.ulp   :  0.0000
...

**Comment by pmur** [comment]
The expected output is correct. The test case assumes the wrong value. I.e written in another identical way:
quantize( -1e-1, 10e-1 ) == -1e-1.

**Comment by pmur** [comment]
The broken test case has been fixed by MR21
