### ISSUE TITLE
Investigate log() results

### ISSUE THREAD

**Issue by tuliom** [libdfp/libdfp#15]
An user reported the following suspicious output for log().
Reproduced on power8.

Output:
2../test-log-d64
...
Test: log (2.718281828459045235360287471352662)
Result:
 is:          9.99999999999999900000e-01 9.9999999999999990e-01
 should be:   1.00000000000000000000e+00 1.0000000000000000e+00
 difference:  1.00000000000000000000e-16 1.0000000000000000e-16
 ulp       :  0.1000
 max.ulp   :  0.0000
...

3../test-log-d128
...
Test: log (2.718281828459045235360287471352662)
Result:
 is:          1.00000000000000000000e+00
9.9999999999999999999999999999999980e-01
 should be:   1.00000000000000000000e+00
1.0000000000000000000000000000000000e+00
 difference: -2.00000000000000000000e-34
-2.0000000000000000000000000000000000e-34
 ulp       : -0.2000
 max.ulp   :  0.0000
...

**Comment by pmur** [comment]
Looking into this... This is a consistent result for the soft dpd, soft bid, and power8 optimized version.

This is likely a trade off of the Taylor series used to approximate the function. Will look into it a bit more.

**Comment by pmur** [comment]
Also, note that the ULP calculation is off by a factor of 10. That should read 1 ULP of error. I was a bit confused as to how it was possible to have a non integral ULP when comparing two floating point numbers.
