### ISSUE TITLE
Investigate log10() results

### ISSUE THREAD

**Issue by tuliom** [libdfp/libdfp#16]
An user reported the following output from log10() as suspicious.
Investigate if they're fine or not.
Reproduced on power8.

Output:
4../test-log10-d64

...
Test: log10 (3.141592653589793238462643383279503)
Result:
 is:          4.97149872694133800000e-01 4.9714987269413380e-01
 should be:   4.97149872694133900000e-01 4.9714987269413390e-01
 difference:  1.00000000000000000000e-16 1.0000000000000000e-16
 ulp       :  1.0000
 max.ulp   :  1.0000
...

5../test-log10-d128

...
Test: log10 (2.718281828459045235360287471352662)
Result:
 is:          4.34294481903251827651e-01
4.3429448190325182765112891891660500e-01
 should be:   4.34294481903251827651e-01
4.3429448190325182765112891891660510e-01
 difference: -1.00000000000000000000e-34
-1.0000000000000000000000000000000000e-34
 ulp       : -1.0000
 max.ulp   :  1.0000
...

**Comment by pmur** [comment]
I think the expected value for test-log10-d128 is wrong. Using bc on a similar input, with much more precision indicates the last digit should be a 0, regardless of rounding mode.

**Comment by tuliom** [comment]
I agree with you.

**Comment by pmur** [comment]
MR21 has fixed the incorrect expected result for d128. The d64 result is within acceptable tolerance.
