### ISSUE TITLE
1.0.16 release

### ISSUE THREAD

**Issue by pmur** [libdfp/libdfp#161]
It's been about a year, a bit of cleanup has been done, a little more TS 18661-2 API has been added, and a few build system fixes found from 1.0.15. This should be a fairly minor release.

I'd like to cut the release around July 12. @stliibm @tuliom do either of you have an concerns, requests, or outstanding issues which should be addressed?

**Comment by stliibm** [comment]
This is fine for me. Thanks Paul.

**Comment by tuliom** [comment]
@pmur I don't think it's mandatory, but it would be great to have PR #162 merged for this version.

**Comment by pmur** [comment]
1.0.16 is released. Thanks all for your feedback!
