### ISSUE TITLE
inconsistent conversion of double values?

### ISSUE THREAD

**Issue by newbie-02** [libdfp/libdfp#178]
Forgive me if I am wrong, I am not experienced in checking installations for their correlations, pls. recheck! 

I have the impression that the conversion of the double representation of decimal 0.1 and decimal 77.4 are logically different. 
for both values the double representation is 'overshot', so much so that decimal rounding leads to a further different value. 

For 0.1 that is overcome in the conversion to _Decimal64, while not for 77.4. ( working on Kali, debian Linux 2021-IV, Intel Xeon processor, 80-bit long doubles, compiler gcc ).  

When converting decimal -> double -> _Decimal64 -> long double I get: 

decimal ->  double                                   -> _Decimal64 -> long double  
     0.1    |   0.100000000000000000555~ |  ???               |  0.10000000000000000000135~
   77.4    | 77.40000000000000568434~   |  ???               |  77.4000000000000100003338~ 

'???' means i have no printout function for decimals, 0.10000000000000000000135 is the correct long double correspondent for decimal 0.1, while 
77.4000000000000100003338    is the pendant to decimal 
77.40000000000001                    and correct for decimal 
77.4                                              would be long double 
77.4000000000000000013877

the first conversion seems reasonable and logical to me, the decimal value is preserved, unfortunately this is not the case with the second one, so it is not suitable to achieve decimal correct calculations. 

performing the conversion double -> long double by 'string math' with intermediate 'shortest roundtripping' decimal string produced by e.g. 'ryu' from Ulf Adams or different flavours of 'dtoa' i get correct long double results.

**Comment by pmur** [comment]
The 64 bit formats have differing levels of precision, and these values will be rounded in each step. The intermediate decimal value is most likely not the starting value in either case, and will likely needing rounding on each conversion.

A conversion from double->long double via strings should be within 1ulp with 17 digits. libdfp provides `strfromd64` with similar semantics to `strfromd`. In both cases, the numbers are rounded to 16 digits which isn't always enough to preserve the original double.

**Comment by newbie-02** [comment]
whatever it takes ... for a meaningful datatype '_Decimalxxx' and a meaningful conversion to and from binary datatypes there is hardly any other option than (decimal)x == (_Decimalxxx)x <~> nearest (bin-FPxxx)x ( with precision capability to represent decimal x ) <~> (shortest roundtripping decimal equivalent)x == (decimal)x. 

Anything else produces yet another useless standard, new irritations and won't be accepted by users or developers. ( there is a nice comic somewhere on the web 'what? we have 14 competing insufficient standards? we need to develop one better standard serving all use cases!!!' -> 15 competing insufficient standards. ) The only one proven, correct and acceptable standard for decimal calculations is what humans have developed in thousands of years, and what is taught in schools. 

from 
    _Decimal64 e = 77.4; 
    long double b = e; 
    printf( " conv. dec->_Decimal64->long double: %.25Lf \n", b ); 
-> 77.40000000000001000033~
i'd say that it's probably the conversion _Decimal64 -> long double being weak, but can't even tell if that's a matter of libdfp, gcc, glibc ??? ... pls. recheck. consider in the range of 77 we do not have 16 decimal digit precision in doubles. 

If rounding is necessary anywhere it shouldn't be duty of the user, for a datatype named 'decimal' it's the responsibility of the library / system to deliver decimal correctness and correct conversions - IMHO.

**Comment by newbie-02** [comment]
from a short check about the scope of the problem: 

in the range [ 64 .. 100 ) plenty figures are affected, all but not limited to xx.4 figures, 99.1, 99.9 and also figures with more digits like 64.51, 64.519 ... 

similar happens in other ranges with 'weak binary representation', e.g. 99999.9 converts to 99999.899999999990001242 and 9.3 to 9.300000000000001000.  

one could say the accuracy in conversion to long double breaks down to double precision in these ranges. it's fairly logical that such went unnoticed for some time as it may be assumed that most developers work in and on 'up to double' precision, long doubles and quads are somewhat exotic. they have little practical relevance, but IMHO are a good tool to spot weaknesses in other datatypes. 

a spontaneous idea is that any variable or constant used in the conversion might be defined as double in the code??? 

would be nice to improve as people looking towards decimal datatypes mainly want to achieve one thing: get rid of such irritations / imprecisions. if the datatype can't deliver it's useless.

**Comment by tuliom** [comment]
> from
> _Decimal64 e = 77.4;
> long double b = e;
> printf( " conv. dec->_Decimal64->long double: %.25Lf \n", b );
> -> 77.40000000000001000033~
> i'd say that it's probably the conversion _Decimal64 -> long double being weak

@newbie-02 It isn't the conversion that is "weak".  It's just that binary floating point types (i.e. Intel's long double) can't represent this number in decimal format (i.e. printf's `%Lf`).
You can confirm it by yourself here:

```
// Build with: gcc -g tst-libdfp.c -ldfp && ./a.out
#define __STDC_WANT_DEC_FP__ 1
#include <stdio.h>

int main (const int argc, const char * const argv[]) {
  _Decimal64 e = 77.4DD;
  long double b = 77.4L;

  printf("_Decimal64:  %.25Df\n", e);
  printf("long double: %.25Lf\n", b );

  return 0;
}
```

In other words: if the decimal representation is important for your application, all variable should always be kept in the decimal format. Whenever a conversion happens information might be lost and it's impossible to reconstruct that information when converting it back to decimal floating point.

**Comment by newbie-02** [comment]
@tuliom, 

thks for your quick reply, 

I'm not working for 'my application', but trying to achieve or come near to decimal correct calculations in general. I thought to check the performance and capabilities of _Decimals, and possibly migrate or do some critical calculations with that datatype, imprecise conversions are a blocker for such. 

have to admit that my system isn't well fitted yet, e.g. it sometimes complains about 'identifier "_Decimal64" is undefined', but seems to work with it ... ??? don't ask me why ... 'newbie', 
and that I was in error assigning '77.4' to e, '77.4DD' works better, 

problem is the 'input evaluation', 

'double 77.4' or decimal string '77.4' -> _Decimal64: deviation, 

all this hiccups and confused mess between different compilers, different versions of them, different extensions and libraries, different options and 'outsmarting' by the compiler using idiosyncratic abbreviations, different understanding of 'long', different encodings for value assignments and print formatting ... are real funbrakes to achieve reliable results in such topics. Actually a world would be better in which you can add 0.2 and 0.1 with a computer without doing a master in numerical analysis first. As complicated as the field is at the moment, it is qualified to drive normal people crazy and to turn weaker characters into alcoholics very quickly. 

Can you link to a working howto or explain how to: 
- to a current 'basic' debian system, 
- with available gcc, 
- add 'decimalxxx' support with: 
- _Decimal32, _Decimal64, _Decimal128 working datatypes, 
- working I/O for these datatypes, and 
- working - decimal value safe!!! - Conversions, each in both directions, between these three data types and each float, double, long double and quad ? 
'decimal value safe!!!' Conversions shall mean the value of the source datatype is stored in the target datatype as exact as it can be represented there, where necessary rounded. Conversions and roundings however in such a way that the value of the 'corresponding decimal' of the origin remains, not! a somehow crooked value which results from deviations between the binary value of a representation and its decimal correspondence. 

And / or might you have a look at the program below, I tried how far I can get, looks poor at the moment. 


// Build with: gcc -g tst-libdfp.c -ldfp && ./a.out 

#define __STDC_WANT_DEC_FP__ 1 
#include <stdio.h>      // reg. e.g. printf, 
#include <stdlib.h>     // reg. e.g. gentenv, 
#include <quadmath.h>   // reg. e.g. float128, 
 
int main (const int argc, const char * const argv[]) 
{ 
    printf( "one value in six different datatypes: \n" ); 
    float xf = 77.4; 
    double xd = 77.4; 
    long double xL = 77.4L; 
//    _Decimal32 xDF = 38.7DF;        // switch frequently, if not reflected in the output the IDE works badly, 
    _Decimal32 xDF = 77.4DF;      // switch frequently, if not reflected in the output the IDE works badly, 
    _Decimal64 xDD = 77.4DD; 
    _Decimal128 xDL = 77.4DL; 
    char btxt[45]; 

    printf( " \n"); 

    printf( "printout: \n" ); 
    printf( "  . . . . . . . . . . . . .  float xf:  %.25f\n",   xf ); 
    printf( "  . . . . . . . . . . . . . double xd:  %.25f\n",   xd ); 
    printf( "  . . . . . . . . . .  long double xL:  %.25Lf\n",  xL ); 
    printf( "  . . . . . . . . . . . .  _Decimal32:  %.25Hf\n",  xDF ); 
    printf( "  . . . . . . . . . . . .  _Decimal64:  %.25Df\n",  xDD ); 
    printf( "  . . . . . . . . . . . . _Decimal128:  %.25DDf\n", xDL ); 

    printf( " \n"); 

    printf( "on my system some of the following conversions are weak, they are marked with 'x>' instead of '->' \n"); 

    printf( "naive conversions to float: \n" ); 
    xf = 77.4; 
    printf( "pure decimal string  . .  -> float xf:  %.25f\n", xf ); 
    xf = xd; 
    printf( "double . . . . . . . . .  -> float xf:  %.25f\n", xf ); 
    xf = xd; 
    printf( "long . . . . . . . . . .  -> float xf:  %.25f\n", xf ); 
    xf = xDF; 
    printf( "_Decimal32 . . . . . . .  -> float xf:  %.25f\n", xf ); 
    xf = xDD; 
    printf( "_Decimal64 . . . . . . .  -> float xf:  %.25f\n", xf ); 
    xf = xDL; 
    printf( "_Decimal128  . . . . . .  -> float xf:  %.25f\n", xf ); 
    xf = 77.4; 

    printf( " \n"); 

    printf( "naive conversions to double: \n" ); 
    xd = 77.4; 
    printf( "pure decimal string  . . -> double xd:  %.25f\n", xd ); 
    xd = xf; 
    printf( "float  . . . . . . . . . x> double xd:  %.25f\n", xd ); 
    xd = xL; 
    printf( "long . . . . . . . . . . -> double xd:  %.25f\n", xd ); 
    xd = xDF; 
    printf( "_Decimal32 . . . . . . . -> double xd:  %.25f\n", xd ); 
    xd = xDD; 
    printf( "_Decimal64 . . . . . . . -> double xd:  %.25f\n", xd ); 
    xd = xDL; 
    printf( "_Decimal128  . . . . . . -> double xd:  %.25f\n", xd ); 
    xd = 77.4; 

    printf( " \n"); 

    printf( "naive conversions to long: \n" ); 
    xL = 77.4; 
    printf( "pure decimal string  . . . x> long xL:  %.25Lf\n", xL ); 
    xL = xf; 
    printf( "float  . . . . . . . . . . x> long xL:  %.25Lf\n", xL ); 
    xL = xd; 
    printf( "double . . . . . . . . . . x> long xL:  %.25Lf\n", xL ); 
    xL = xDF; 
    printf( "_Decimal32 . . . . . . . . -> long xL:  %.25Lf\n", xL ); 
    xL = xDD; 
    printf( "_Decimal64 . . . . . . . . -> long xL:  %.25Lf\n", xL );  
    xL = xDL; 
    printf( "_Decimal128  . . . . . . . -> long xL:  %.25Lf\n", xL ); 
    xL = 77.4L; 

    printf( " \n"); 

    printf( "naive conversions to _Decimal32: \n" ); 
    xDF = 77.4; 
    printf( "pure decimal string -> _Decimal32 xDF:  %.25Hf\n", xDF ); 
    xDF = xf; 
    printf( "float  . . . . . .  -> _Decimal32 xDF:  %.25Hf\n", xDF ); 
    xDF = xd; 
    printf( "double . . . . . .  -> _Decimal32 xDF:  %.25Hf\n", xDF ); 
    xDF = xL; 
    printf( "long   . . . . . .  -> _Decimal32 xDF:  %.25Hf\n", xDF ); 
    xDF = xDD; 
    printf( "_Decimal64 . . . .  -> _Decimal32 xDF:  %.25Hf\n", xDF ); 
    xDF = xDL; 
    printf( "_Decimal128  . . .  -> _Decimal32 xDF:  %.25Hf\n", xDF ); 
    xDF = 77.4DF; 

    printf( " \n"); 

    printf( "naive conversions to _Decimal64: \n" ); 
    xDD = 77.4; 
    printf( "pure decimal string x> _Decimal64 xDD:  %.25Df\n", xDD ); 
    xDD = xf; 
    printf( "float  . . . . . .  x> _Decimal64 xDD:  %.25Df\n", xDD ); 
    xDD = xd; 
    printf( "double . . . . . .  x> _Decimal64 xDD:  %.25Df\n", xDD ); 
    xDD = xL; 
    printf( "long   . . . . . .  -> _Decimal64 xDD:  %.25Df\n", xDD ); 
    xDD = xDF; 
    printf( "_Decimal64 . . . .  -> _Decimal64 xDD:  %.25Df\n", xDD ); 
    xDD = xDL; 
    printf( "_Decimal128  . . .  -> _Decimal64 xDD:  %.25Df\n", xDD ); 
    xDD = 77.4DD; 

    printf( " \n"); 

    printf( "naive conversions to _Decimal128: \n" ); 
    xDL = 77.4; 
    printf( "pure decimal string x> _Decimal128 xDL: %.25DDf\n", xDL ); 
    xDL = xf; 
    printf( "float  . . . . . .  x> _Decimal128 xDL: %.25DDf\n", xDL ); 
    xDL = xd; 
    printf( "double . . . . . .  x> _Decimal128 xDL: %.25DDf\n", xDL ); 
    xDL = xL; 
    printf( "long   . . . . . .  x> _Decimal128 xDL: %.25DDf\n", xDL ); 
    xDL = xDF; 
    printf( "_Decimal32 . . . .  -> _Decimal128 xDL: %.25DDf\n", xDL ); 
    xDL = xDD; 
    printf( "_Decimal64 . . . .  -> _Decimal128 xDL: %.25DDf\n", xDL ); 
    xDL = 77.4DL; 

    printf( " \n"); 

    printf( "that's about 11 in 36 conversions weak, weaknesses esp. in conversions towards decimal datatypes, \n" ); 
    printf( "too many to base a reliable mathematics on it. \n" ); 

    printf( " \n"); 

    printf( "correct value is representable: \n" ); 
    xDD = xL; 
    printf( "long   . . . . . .  -> _Decimal64 xDD:  %.25Df\n", xDD ); 

    printf( " \n"); 

return 0;
}

**Comment by tuliom** [comment]
> I'm not working for 'my application', but trying to achieve or come near to decimal correct calculations in general. I thought to check the performance and capabilities of _Decimals, and possibly migrate or do some critical calculations with that datatype

@newbie-02 , have you looked at multiple-precision libraries? You seem to be describing a problem that is ideally solved by them.
Here is a sample code using MPFR: https://www.mpfr.org/sample.html

**Comment by newbie-02** [comment]
@tuliom:  
  
tks for that hint, it unveils a shortcoming to express my ideas correctly. i'm not looking for exotic, costly, special solutions, but attempting to plug the leaks in common programs, esp. spreadsheets. they - or just generally other programs that enjoy fast FP calculations - are / form 'well-established systems', with a few shortcomings, and a few inadequate attempts to correct or whitewash them.  
  
There are two approaches to improve parts of it, one would be to use other data types where - e.g. with _Decimals - parts of the problem sources is omitted, the inaccurate representation,  
  
another for the objective assessment of the quality of FP calculations - which one needs to distinguish 'trial and error' improvements in improvements vs. exacerbations - to have differently calculated 'independent' references available.  
  
Using a simple example: the goal is to correct the error of 0.2 + 0.1 != 0.3, while losing as little precision as possible. Not to use more superfluous digits or bits and / or to only push the (rounding) errors further out.  

And do that - improving the calculations - in a minimal invasive way, and stay compatible with installed systems, not to rewrite the programs or similar. For this purpose _Decimals seemed promisingly to me. but would urgently need correct conversion. ( which would be good in general? )  
  
Isn't the different conversion of 0.1 and 77.4 a shortcoming big enough and underminig the usability of _Decimals datatypes that the project will try to improve?

**Comment by tuliom** [comment]
> Isn't the different conversion of 0.1 and 77.4 a shortcoming big enough and underminig the usability of _Decimals datatypes that the project will try to improve?

No, for the reasons that @pmur and I already explained.
If the precision is so important for the problem you're trying to solve, you must not have intermediate conversions. Be careful with implicit conversions too.

With that said, I'm closing this issue.

**Comment by newbie-02** [comment]
after some years ... I think I can pinpoint somewhat  
better what I'd like for / from libdfp.  
  
It's a little longer, but provides a solution which might  
strengthen libdfp significantly, read when you have  
some spare time.  
  
There is a shift / ambiguity that some decimal values  
are represented with binary values that are 'closest'  
to them in binary, but not in decimal, so decimal rounding  
does not work to get the decimal origin back.  
  
Let's take 77.4 above, in this range IEEE doubles have  
not quite 16 decimal digits of precision, and only  
77.39999999999999,  
77.4, and 
77.40000000000002 can be represented, for 
77.4000000000001 a binary deputy is missing.   
  
Actually! it is not missing, the double value of  
which the decimal content is about  
77.4000000000000056843418861... would match  
( not good but best ), BUT! that is what IEEE or  
'modern IT' steals away for 77.4, because a  
number system in which decimal 77.4 is missing  
is difficult to explain to normal, simple-minded  
users.  
The assignment is thus:  
```
Decimal:              binary:  
77.39999999999999 <-> 77.3999999999999914735
77.4              <-> 77.4000000000000056843
77.40000000000002 <-> 77.4000000000000198952  
```  
and here 77.4 can only be recovered with rounding  
if you round to 15 or fewer decimal digits, but this  
would produce other problems.  
If you / we now want to recover the 77.4 from the  
77.4000000000000056843... 'for the naive user',  
or for a meaningful consistency / coherence, for  
example to assign a _Decimal64 value to the double  
value, then there is a method, 'SRT', Shortest Round  
Tripping', designed by Steele and White in the 1980s,  
and since 2018 with 'ryu' by Ulf Adams reasonably  
performant available, 
But that would be 'string-math', a bit cumbersome  
and embarrassing, 'dragonbox' offers since ???? an  
alternative that can return a triple of sign, exponent  
and significand. It is firstly fast, and secondly can  
be easily converted to a _Decimal64 value.  
My coding skills have grown that I in general could  
try to code a conversion myself, but would like it better  
if a pro can do, once to have it cleanly integrated in  
libdfp, and I'm not good in understanding the code  
style of libdfp.  
  
Thus wish: 'b642d64' or similar, binary64 -> 'dragonbox  
SRT Triple' -> _Decimal64 .  
  
Think it would ease the use / adaption of libdfp for plenty  
people with existing data to have a value preserving  
conversion.  
  
short program which shows the content and conversion error:  
  
```
        volatile double x4d = 77.4; 
        volatile _Decimal64 e = x4d; 
        volatile long double b = e; 
 
        printf("double:      %.25f\n", x4d ); 
        printf("_Decimal64:  %.25Df\n", e); 
        printf("long double: %.25Lf\n", b ); 
 
```  
would like to reopen but lack the power or the role :-(
