### ISSUE TITLE
MATH: POW: fail with powd64( 2, -1279 ) -> 0

### ISSUE THREAD

**Issue by newbie-02** [libdfp/libdfp#188]
can't say if bug, intentional, mistake by me, missed reading the manual?  ...  
managed to implement using of math functions in an application and in 'pure-C' code,  
experience the result '0' for the calculation in the subject,  
tried to put it in a small testprog:  
```  
        volatile _Decimal64 x1DD = 2.0DD; 
        volatile _Decimal64 x2DD = -1278.0DD; 
        printf( "powd64( 2.0DD, -1278.0DD ) : %.17DE \n", powd64( x1DD, x2DD ) ); 
        printf( "exp2d64( -1278.0DD )       : %.17DE \n", exp2d64( x2DD ) ); 
        x2DD = -1279.0DD; 
        printf( "powd64( 2.0DD, -1279.0DD ) : %.17DE \n", powd64( x1DD, x2DD ) ); 
        printf( "exp2d64( -1279.0DD )       : %.17DE \n", exp2d64( x2DD ) ); 
```  
output:  
```  
powd64( 2.0DD, -1278.0DD ) : 1.92161128896030000E-385 
exp2d64( -1278.0DD )       : 1.92161128896030000E-385 
powd64( 2.0DD, -1279.0DD ) : 0.00000000000000000E+00 
exp2d64( -1279.0DD )       : 9.60805644480100000E-386 
```  
_assume!_  fail based on 1278 being the max. **positive** exponent,  
but negative should reach out to -1324 ( quasi denormals ).  
_assume!_  similar fails for other powers ...

**Comment by newbie-02** [comment]
thanks for confirmation,  
`x^-y = 1/(x^y)` isn't a given in asymmetrical limited domains.  
Curious how long that bug survived, is it 'documented'?  
Affected: all powers x^-y where x^y exceeds MAX, thus I'd add 'critical'.  
If no better idea for fixing:  
``` 
... other calculations,  
if( result == 0 ) 
        result = 'recalculate with other ( slow - precise ) algorithm'; 
return( result ); 
```  
Regarding performance: apply same algo for powd32 and powd128?

**Comment by pmur** [comment]
powd{32,128} should be less susceptible to this particular issue. This library is quite old, and the test suite is lacking in many places.

I am adding pow support to the test suite, and I will try some workaround to avoid divisor overflow.

**Comment by newbie-02** [comment]
But am I right that this project is 'the' math library for _Decimalxxx datatypes  
and is under active development? Or is it outdated, overtaken by others or  
_Decimals 'dead'?

**Comment by pmur** [comment]
This is the GNU decimal float library, and the only supported OSS decimal float library I know of. Many of the transcendental functions exist for orthogonality with binary float.

It's not dead, but the user base is both small and quiet. Thus, it moves slowly.

**Comment by newbie-02** [comment]
hmmmm ... there are more odd 'corner cases' laying around?  
```  
        volatile _Decimal64 x1DD = -1E-398DD; 
        volatile _Decimal64 x2DD = -1.0DD; 
        printf( "nextafterd64( %.17DE, %.17DE ) : %.17DE \n", x1DD, x2DD, nextafterd64( x1DD, x2DD ) );
        x1DD = -2E-398DD; 
        printf( "nextafterd64( %.17DE, %.17DE ) : %.17DE \n", x1DD, x2DD, nextafterd64( x1DD, x2DD ) ); 
```  
output:  
```  
nextafterd64( -1.00000000000000000E-398, -1.00000000000000000E+00 ) : 0.00000000000000000E+00 
nextafterd64( -2.00000000000000000E-398, -1.00000000000000000E+00 ) : -3.00000000000000000E-398 
```  
think the first result is wrong.  
    
think to gather more use libdfp should provide:  
- easier to find,  
- easier to implement,  
- cover correct math to best possible extent.

**Comment by newbie-02** [comment]
If I'm not mistaken in any respect - which is always an option -  
the nextafter problem is sourced by a questionable statement in  
`ieee754r/nextafter32.c`, and can be corrected by the following patch:  
( github sucks, they reject upload of a git diff file even when named *.patch )  
```  
      return x; 
    } 
  DEC_TYPE epsilon = SUBNORMAL_MIN; 
//   if (x == -SUBNORMAL_MIN)                                                                     //d- edit b.s. - TESTING - 2024-01-29: seeking wrong result for nextafter( -subnormal_min, -1 ), 
//     return -0;                                                                                 //d- 
 
  if (x > y) 
    { 
```  
evtl. the statement would be meaningful one 'else' deeper to  
get a -0 for the 'up' nextafter of minus_min_denormal?

**Comment by newbie-02** [comment]
hmmmmm..... likely 'me bad', but tried my best and see some problems.  
  
I did this:  
```  
'git clone https://github.com/pmur/libdfp.git libdfp-pmur',  
'cd libdfp-pmur',  
'./configure',  
'make',  
'sudo make install',  
'make check',  
```  
and A.) lost some precision in nextafters:  
```  
        volatile _Decimal64 x1DD = 0.0DD; 
        volatile _Decimal64 x2DD = 1.0DD; 
        printf( "nextafterd64( %.17DE, %.17DE )       :  %.17DE \n", x1DD, x2DD, nextafterd64( x1DD, x2DD ) ); 
        x2DD = -1.0DD; 
        printf( "nextafterd64( %.17DE, %.17DE )      : %.17DE \n", x1DD, x2DD, nextafterd64( x1DD, x2DD ) ); 
```  
the output changed from:  
```  
nextafterd64( 0.00000000000000000E+00, 1.00000000000000000E+00 )       :  1.00000000000000000E-398 
nextafterd64( 0.00000000000000000E+00, -1.00000000000000000E+00 )      : -1.00000000000000000E-398 
```  
to:  
```  
nextafterd64( 0.00000000000000000E+00, 1.00000000000000000E+00 )       :  1.00000000000000000E-16 
nextafterd64( 0.00000000000000000E+00, -1.00000000000000000E+00 )      : -1.00000000000000000E-16 
```  
note the changed magnitude!  
Add. B.) lost the effect of setting the rounding mode:  
```  
        if( r != FE_DEC_TONEAREST ) { 
                printf( "The DFP rounding mode is not FE_DEC_TONEAREST.\n" ); 
                if( fe_dec_setround( FE_DEC_TONEAREST ) == -1 ) { 
                        perror( "fe_dec_setround" ); 
                        exit( -1 ); 
                } 
        } 
        printf( "The DFP rounding mode has been set to FE_DEC_TONEAREST.\n" ); 
 
        if( ( r = fe_dec_getround() ) == -1 ) { 
                perror( "fe_dec_getround" ); 
                exit( -1 ); 
        } 
        printf( "The Decimal floating point rounding mode is %d\n", r ); 
 
// necc. in code:                                                                       // assume was to get something working despite the cheating compiler optimizes out the use of libdfp, 
//      _Decimal128 temp = strtoflt128( "1", NULL );                                    // this line is required to enable print formatting with 'DD'? 
 
        volatile _Decimal64 x1DD = 8.000000000000001DD; 
        volatile _Decimal64 x2DD = 8.000000000000002DD; 
        volatile _Decimal64 x3DD = 5.0E-16DD; 
        printf("%.17DE \n", x1DD + x3DD ); 
        printf("%.17DE \n", x2DD + x3DD ); 
 
        if ((r = fe_dec_getround()) == -1 ){ 
                perror( "fe_dec_getround" ); 
                exit( -1 ); 
        } 
        printf( "The Decimal floating point rounding mode is %d\n", r ); 
 
        if (r != FE_DEC_TONEARESTFROMZERO ){ 
                printf( "The DFP rounding mode is not FE_DEC_TONEARESTFROMZERO.\n" ); 
///             if( fe_dec_setround( FE_DEC_TONEARESTFROMZERO ) == -1 ){ 
                if( fe_dec_setround( 4 ) == -1 ){ 
                        perror( "fe_dec_setround" ); 
                        exit( -1 ); 
                } 
        } 
        printf( "The DFP rounding mode has been set to FE_DEC_TONEARESTFROMZERO.\n" ); 
 
        if( (r = fe_dec_getround()) == -1 ) { 
                perror( "fe_dec_getround" ); 
                exit( -1 ); 
        } 
        printf( "The Decimal floating point rounding mode is %d\n", r ); 
 
        printf( "%.17DE \n", x1DD + x3DD ); 
        printf( "%.17DE \n", x2DD + x3DD ); 
 
        if( ( r = fe_dec_getround() ) == -1 ) { 
                perror( "fe_dec_getround" ); 
                exit( -1 ); 
        } 
        printf( "The Decimal floating point rounding mode is %d\n", r ); 
```  
formerly produced:  
```  
The Decimal floating point rounding mode is 0
8.00000000000000200E+00 
8.00000000000000200E+00 
The Decimal floating point rounding mode is 0
The DFP rounding mode is not FE_DEC_TONEARESTFROMZERO.
The DFP rounding mode has been set to FE_DEC_TONEARESTFROMZERO.
The Decimal floating point rounding mode is 4
8.00000000000000200E+00 
8.00000000000000300E+00 
The Decimal floating point rounding mode is 4
```  
note that changing the mode changed the result to ~3!  
and now:  
```  
The Decimal floating point rounding mode is 0
8.00000000000000200E+00 
8.00000000000000200E+00 
The Decimal floating point rounding mode is 0
The DFP rounding mode is not FE_DEC_TONEARESTFROMZERO.
The DFP rounding mode has been set to FE_DEC_TONEARESTFROMZERO.
The Decimal floating point rounding mode is 4
8.00000000000000200E+00 
8.00000000000000200E+00 
The Decimal floating point rounding mode is 4
```  
note that it's no longer rounded up to ~000003!

**Comment by pmur** [comment]
I wouldn't recommend using the master branch from my clone. I don't update it. I just use the clone to push branches to merge into libdfp. Whatever you built is likely very old, and links against the libbid inside libgcc which doesn't support rounding mode. (I am guessing you are building running on arm64/amd64?)

I am guessing you wanted to use my murp/fix-pow  branch instead?

**Comment by newbie-02** [comment]
ok, that looks better ... still learning,  
  
Do you also have an idea what I am doing wrong to paralyze my system with:  
`printf( "powd64( 2.0DD, -2147483648.0DD ) : %.17DE \n", powd64( 2.0DD, -2147483648.0DD ) );`  
100 percent CPU activity on one core, no result.  
And:  
`printf( "powd64( 2.0DD, -4294967296.0DD ) : %.17DE \n", powd64( 2.0DD, -4294967296.0DD ) );`  
resulting in 1.00000000000000000E+00 is IMHO questionable.

**Comment by pmur** [comment]
powd64/powd32 does not seem to handle large integer powers correctly. I can fix that one too.

**Comment by pmur** [comment]
I reworked powd64 to behave with large exponents, and the increased precision should allow it correctly compute large exponents that don't overflow. One of the test cases I added has about 600 ULPs of error if computed with lower precision. 

I haven't tested powd64 for accuracy. That belongs in a separate issue.

**Comment by newbie-02** [comment]
AFAIS the powers are correct now, checking the performance I see  
~factor 1000 slow vs. binary calculation,  punching through to  
~factor 15 in an application calculating ~256k powers.  
  
Curious if that's necessary or can be improved?  
  
Naive approach: There is any mathematical algorithm to calculate  
pow, using 'simplier math' in some combination, simplier math is -  
as far as I have seen and tested - slower in decimal than binary, but  
by about factor 10. Of course there may be optimizations in hardware  
or well elaborated algorithms propelling binary ... but factor 100?  
  
Think / hope someone here can shed some light on this, think it's not  
qualified to open an issue until someone says improvement is possible.

**Comment by newbie-02** [comment]
hello @pmur, thanks for caring,  
  
my - naive - idea: operands, some math like multiplications,  
additions, subtractions ... -> result in power( x, y ), meaningful to  
take as much extratime as the simple math functions are slow,  
observation: simple math factor ~10, power factor ~1000 :-(  
  
a test program: 
[powd64_slow.c.txt](https://github.com/libdfp/libdfp/files/14251352/powd64_slow.c.txt)
rename to *.c ( github sucks ) and provide a copy of /usr/local/include/dfp locally, here dfp/math.h didn't manage to pull system math.h, resulting in missing prototype for power.   
  
output:  
```  
  └─$ ./powd64_slow                                 
0.001747; 1000000; 7.8500000000000000E+01; x7d = x5d + x6d 
0.011326; 1000000; 7.850000000000000E+01; x7DD = x5DD + x6DD 
0.020238; 1000000; 3.6535446722156005E+06; x7d = pow( x5d, x6d ) 
15.323594; 1000000; 3.653544672215601E+06; x7DD = powd64( x5DD, x6DD ) 
```

**Comment by newbie-02** [comment]
_assume_ when using Decimal128 values for intermediates  
you are kicking the system out of options to use  
SSE / SSE2 / AVX / AVX2 / AVX512 math, and thus pull it to  
slow algorithms?

**Comment by newbie-02** [comment]
Powers play a major role in my applications and are also generally  
important for rounding. Thus I had a look to see if I could find a  
faster solution. If substitution calculations with binary data types  
are allowed? 
  
'(_Decimal64)powq( ( __float128)x, (__float128)y )' seems to give  
  
A.) same results as powd64, and is  
B.) about 7 times faster.  
Errors would theoretically be possible where the powq result after  
the 16 digits required for dec64 should consist of 499999999999999999  
or 500000000000000000 and is pushed over the '5 border' to the other  
side by an error in the last digit, or where ties to even hits in the  
__float128 -> _Decimal64 conversion. Both between impossible and  
very very very ( 1:10^18? ) unlikely.
