### ISSUE TITLE
libdfp.so.1 is not created on cross compiler

### ISSUE THREAD

**Issue by rzinsly** [libdfp/libdfp#2]
While trying to build libdfp on cross with AT, the libdfp.so.1 is not created and no error message is displayed.
This is the log:

+Linking shared object files into libdfp-1.0.9.so.
/home/rzinsly/AT/eight/at-next-8.0/bin/powerpc64-linux-gnu-gcc  -DSHARED -O3 -Wl,-zrelro -fpic -g -m64 -mcpu=power7  -shared -Wl,-soname,libdfp.so.1 -Bsymbolic -Wl,--whole-archive libdecnumber/libdecnumber.a -Wl,--no-whole-archive -Wl,--version-script,libdfp.map dfptypeconv.os mapround.os decode.os fmt_d32.os fmt_d64.os fmt_d128.os fe_decround.os strtod32.os strtod64.os strtod128.os wcstod32.os wcstod64.os wcstod128.os printf_dfp.os init_dfp.os dpd-private.os binpowof10.os decpowof2.os decNumberMath.os acosd32.os acosd64.os acosd128.os acoshd32.os acoshd64.os acoshd128.os asind32.os asind64.os asind128.os asinhd32.os asinhd64.os asinhd128.os atan2d32.os atan2d64.os atan2d128.os atand32.os atand64.os atand128.os atanhd32.os atanhd64.os atanhd128.os cbrtd32.os cbrtd64.os cbrtd128.os ceild32.os ceild64.os ceild128.os copysignd32.os copysignd64.os copysignd128.os cosd32.os cosd64.os cosd128.os coshd32.os coshd64.os coshd128.os erfd32.os erfd64.os erfd128.os exp2d32.os exp2d64.os exp2d128.os expd32.os expd64.os expd128.os expm1d32.os expm1d64.os expm1d128.os fabsd32.os fabsd64.os fabsd128.os fdimd32.os fdimd64.os fdimd128.os isfinited32.os isfinited64.os isfinited128.os issignalingd32.os issignalingd64.os issignalingd128.os floord32.os floord64.os floord128.os fmad32.os fmad64.os fmad128.os fmaxd32.os fmaxd64.os fmaxd128.os fmind32.os fmind64.os fmind128.os fmodd32.os fmodd64.os fmodd128.os fpclassifyd32.os fpclassifyd64.os fpclassifyd128.os frexpd32.os frexpd64.os frexpd128.os hypotd32.os hypotd64.os hypotd128.os ilogbd32.os ilogbd64.os ilogbd128.os llogbd32.os llogbd64.os llogbd128.os isgreaterd32.os isgreaterd64.os isgreaterd128.os isgreaterequald32.os isgreaterequald64.os isgreaterequald128.os isinfd32.os isinfd64.os isinfd128.os islessd32.os islessd64.os islessd128.os islessequald32.os islessequald64.os islessequald128.os islessgreaterd32.os islessgreaterd64.os islessgreaterd128.os isnand32.os isnand64.os isnand128.os isnormald32.os isnormald64.os isnormald128.os isunorderedd32.os isunorderedd64.os isunorderedd128.os ldexpd32.os ldexpd64.os ldexpd128.os lgammad32.os lgammad64.os lgammad128.os llquantexpd32.os llquantexpd64.os llquantexpd128.os llrintd32.os llrintd64.os llrintd128.os llroundd32.os llroundd64.os llroundd128.os log10d32.os log10d64.os log10d128.os log1pd32.os log1pd64.os log1pd128.os log2d32.os log2d64.os log2d128.os logbd32.os logbd64.os logbd128.os logd32.os logd64.os logd128.os lrintd32.os lrintd64.os lrintd128.os lroundd32.os lroundd64.os lroundd128.os modfd32.os modfd64.os modfd128.os nand32.os nand64.os nand128.os nearbyintd32.os nearbyintd64.os nearbyintd128.os nextafterd32.os nextafterd64.os nextafterd128.os nexttowardd32.os nexttowardd64.os nexttowardd128.os powd32.os powd64.os powd128.os quantized32.os quantized64.os quantized128.os quantumd32.os quantumd64.os quantumd128.os remainderd32.os remainderd64.os remainderd128.os rintd32.os rintd64.os rintd128.os roundd32.os roundd64.os roundd128.os roundevend32.os roundevend64.os roundevend128.os samequantumd32.os samequantumd64.os samequantumd128.os scalblnd32.os scalblnd64.os scalblnd128.os scalbnd32.os scalbnd64.os scalbnd128.os signbitd32.os signbitd64.os signbitd128.os sind32.os sind64.os sind128.os sinhd32.os sinhd64.os sinhd128.os sqrtd32.os sqrtd64.os sqrtd128.os tand32.os tand64.os tand128.os tanhd32.os tanhd64.os tanhd128.os tgammad32.os tgammad64.os tgammad128.os truncd32.os truncd64.os truncd128.os addsd3.os adddd3.os addtd3.os divsd3.os divdd3.os divtd3.os eqsd2.os eqdd2.os eqtd2.os extendsddd2.os extendsdtd2.os extendddtd2.os extendsfsd.os extendsddf.os extendsdtf.os extendsfdd.os extenddfdd.os extendddtf.os extendsftd.os extenddftd.os extendtftd.os fixsdsi.os fixddsi.os fixtdsi.os fixsddi.os fixdddi.os fixtddi.os fixunssdsi.os fixunsddsi.os fixunstdsi.os fixunssddi.os fixunsdddi.os fixunstddi.os floatsisd.os floatsidd.os floatsitd.os floatdisd.os floatdidd.os floatditd.os floatunssisd.os floatunssidd.os floatunssitd.os floatunsdisd.os floatunsdidd.os floatunsditd.os gesd2.os gedd2.os getd2.os gtsd2.os gtdd2.os gttd2.os lesd2.os ledd2.os letd2.os ltsd2.os ltdd2.os lttd2.os mulsd3.os muldd3.os multd3.os nesd2.os nedd2.os netd2.os subsd3.os subdd3.os subtd3.os truncddsd2.os trunctddd2.os trunctdsd2.os truncsdsf.os truncdfsd.os trunctfsd.os truncddsf.os truncdddf.os trunctfdd.os trunctdsf.os trunctddf.os trunctdtf.os unordsd2.os unorddd2.os unordtd2.os classify.os -o libdfp-1.0.9.so -lm

+Creating linker .so symlink libdfp.so -> libdfp-1.0.9.so
ln -f -s libdfp-1.0.9.so libdfp.so

+Running ldconfig to create the library compat symlink libdfp.so.1 -> libdfp-1.0.9.so
/sbin/ldconfig -l libdfp-1.0.9.so
/sbin/ldconfig: No link created since soname could not be found for libdfp-1.0.9.so

libdfp was configured with:
CFLAGS='-Wl,-zrelro -g -O3 -m64' CXXFLAGS='-g -O3 -m64' ./configure --build=x86_64-pc-linux-gnu --host=powerpc64-linux-gnu --with-backend=libdecnumber --enable-decimal-float=dpd --with-cpu=power7

The commit https://github.com/libdfp/libdfp/commit/beeb2384ea14b5526b9dbca36dcdc27c7bc3f219 was tested with the changes in: https://github.com/libdfp/libdfp/commit/a42c6fb4c9e3562a00551ff972ebdbb423999c4a applied.

**Comment by gftg85** [comment]
The same happens with commit ID bced2369048b5ec4b49ad72f96bb61013fa80f4a

**Comment by tuliom** [comment]
This bug should now be fixed with commit 32101191.
