### ISSUE TITLE
Conversions wrongly produce zero instead of subnormal

### ISSUE THREAD

**Issue by jsm28** [libdfp/libdfp#30]
At least some libdfp conversions between decimal and binary types wrongly convert values in the subnormal range of the target type to zero instead of a subnormal.  For example, for conversions from _Decimal128 to double, the attached test (on POWER8 little-endian) outputs:

0x0.012688b70e62bp-1022 0x0p+0

whereas if I use the libgcc conversions I get the expected:

0x0.012688b70e62bp-1022 0x0.012688b70e62bp-1022
[subnormal.txt](https://github.com/libdfp/libdfp/files/67516/subnormal.txt)

**Comment by racardoso** [comment]
This is related to #32. Now it's returning a 0x0.0000000000001p-1022 since it's considering a obvious underflow. Maybe my #61 is incomplete. I am working on this now.

**Comment by racardoso** [comment]
The problem here is that `BINPOWOF10_LIMIT` is E308 (for double) that's the exponent for max and min normal number but, the min subnormal exponent is E324 (4.9406564584124654e-32).

**Comment by racardoso** [comment]
This is already fixed. Although, we still have some problems with subnormal numbers there's already issues #32 #71 #29 that point that issues. So I am closing this.
