### ISSUE TITLE
Conversions incorrect on overflow

### ISSUE THREAD

**Issue by jsm28** [libdfp/libdfp#31]
At least some libdfp conversions between decimal and binary types wrongly always produce an infinity for obviously overflowing results, without taking account of the rounding mode (the relevant rounding mode is that for the radix of the target type, not the source type).  For example, the attached test converting 1e1000DL to double produces (on POWER8 little-endian):

inf

but the expected result, as with the libgcc conversions, is:

0x1.fffffffffffffp+1023
[overflow.txt](https://github.com/libdfp/libdfp/files/67519/overflow.txt)

**Comment by racardoso** [comment]
Closed via  bc38bdf
