### ISSUE TITLE
Conversions missing "inexact" exception

### ISSUE THREAD

**Issue by jsm28** [libdfp/libdfp#33]
At least some libdfp conversions between decimal and binary types wrongly fail to raise the "inexact" exception for inexact results.  For example, the attached test prints

inexact not raised

instead of the expected

inexact raised as expected

(libgcc conversions via strings have the same issue because glibc strtod fails to raise "inexact", which is a strtod bug; this bug report is only about the libdfp issue).
[testinex.txt](https://github.com/libdfp/libdfp/files/67525/testinex.txt)

**Comment by racardoso** [comment]
Related with task #34.

**Comment by racardoso** [comment]
I am checking if I have to clean this inexact if the result is a normal number. If I have to, I will have to check any exceptions before the code and then check if the number is not a subnormal in the end.
