### ISSUE TITLE
Incremental builds are broken

### ISSUE THREAD

**Issue by pmur** [libdfp/libdfp#36]
The build system does not check included for files, leaving incremental builds in broken states.

**Comment by gftg85** [comment]
I confirm this.

Steps to reproduce:

1. ./bootstrap
1. ./configure
1. make
1. echo "#error No error?" >> include/dfp.h
1. make

The last make should report the error, but it doesn't.

Cleaning, then re-building produces the expected behavior:

1. make clean
1. make

```
In file included from init_dfp.c:25:0:
./include/dfp.h:39:2: error: #error No error?
#error No error?
```
