### ISSUE TITLE
check-localplt is failing on Debian 8 ppc

### ISSUE THREAD

**Issue by tuliom** [libdfp/libdfp#38]
I noticed this recently, but it seems to be affecting older revisions.
I was able to reproduce it on Debian 8.  The kernel is ppc64, but I was building for ppc.

    configure --build=powerpc-linux --host=powerpc-linux
    ...
    $ cat check-localplt.out 
    Extra PLT reference: libdfp.so: register_printf_dfp@@LIBDFP_1.0.0
    Missing required PLT reference: libdfp.so: register_printf_dfp

**Comment by pmur** [comment]
Looks like our scripts are a bit of out date. Some versions of readelf append the symbol version. glibc fixed this a while back. I'll synch our copy up.

**Comment by tuliom** [comment]
LGTM
