### ISSUE TITLE
test-exp-d32/64 failed with exp (88.72269439697265625)

### ISSUE THREAD

**Issue by Zhengtong** [libdfp/libdfp#53]
Test: exp (88.72269439697265625)
Result:
 is:          3.40231600000000000000e+38  3.4023160e+38
 should be:   3.40233100000000000000e+38  3.4023310e+38

Not sure if this is a bug of the test suit. would anyone please have a look at it ?

**Comment by tuliom** [comment]
Which architecture are you using?

**Comment by Zhengtong** [comment]
ppc64le

**Comment by tuliom** [comment]
This issue is duplicated.
