### ISSUE TITLE
Failed with test-log-d128/64 on 2.718281828459045235360287471352662

### ISSUE THREAD

**Issue by Zhengtong** [libdfp/libdfp#54]
test-log-d64:
Test: log (2.718281828459045235360287471352662)
Result:
 is:          9.99999999999999900000e-01  9.999999999999999e-01
 should be:   1.00000000000000000000e+00  1.000000000000000e+00
 difference:  1.00000000000000000000e-16  1.000000000000000e-16
 ulp       :  0.1000
 max.ulp   :  0.0000

test-log-d128:
Test: log (2.718281828459045235360287471352662)
Result:
 is:          1.00000000000000000000e+00  9.999999999999999999999999999999998e-01
 should be:   1.00000000000000000000e+00  1.000000000000000000000000000000000e+00
 difference:  2.00000000000000000000e-34  2.000000000000000000000000000000000e-34
 ulp       :  0.2000
 max.ulp   :  0.0000

**Comment by tuliom** [comment]
Which architecture are you using?

**Comment by Zhengtong** [comment]
on ppc64le platform

**Comment by tuliom** [comment]
In my tests, this isn't being reported as an error, which is expected.
In libdfp, we consider an error if the ULP is greater than 0.5.
Per your output, it seems it wasn't classified as an error too, because it doesn't have the string "Failure: " anywhere.

**Comment by Zhengtong** [comment]
Thanks for the clarification @tuliom
