### ISSUE TITLE
log10 (3.141592653589793238462643383279503) failed with test-log10-d64

### ISSUE THREAD

**Issue by Zhengtong** [libdfp/libdfp#55]
Test: log10 (3.141592653589793238462643383279503)
Result:
 is:          4.97149872694133800000e-01  4.971498726941338e-01
 should be:   4.97149872694133900000e-01  4.971498726941339e-01
 difference:  1.00000000000000000000e-16  1.000000000000000e-16
 ulp       :  1.0000
 max.ulp   :  1.0000

**Comment by tuliom** [comment]
Hi @Zhengtong , which architecture are you using?

**Comment by Zhengtong** [comment]
I am using ppc64le platform

**Comment by tuliom** [comment]
The output in this case is in the maximum ULP range.
So, this isn't a problem.
I also confirmed that it isn't being incorrectly classified as error in the tests.

**Comment by Zhengtong** [comment]
Thanks, it make sense
