### ISSUE TITLE
s390x test failures

### ISSUE THREAD

**Issue by frediz** [libdfp/libdfp#56]
Hi,
while compiling on s390x, I noticed several tests failing.
Note that this was done on a qemu guest, on Debian Unstable (I'm maintaining the Debian package).
Hardening was disabled and test ouput should be displayed within the log.
Here is the build log : 

F.

[libdfp_1.0.13-2-1.buildlog.txt](https://github.com/libdfp/libdfp/files/1097884/libdfp_1.0.13-2-1.buildlog.txt)

**Comment by stliibm** [comment]
Hi,

You've compiled with: gcc ...-march=zEC12 ... -mzarch ...
And according to the buildlog, you've got several Illegal instructions.

Which CPU do you use? >= zEC12?
Note: As far as I know, the qemu emulator lacks support for decimal-floating-point instructions.

Stefan

**Comment by tuliom** [comment]
@frediz were you able to pass the tests?
