### ISSUE TITLE
libdecnumber

### ISSUE THREAD

**Issue by injinj** [libdfp/libdfp#78]
Libdecnumber doesn't appear to be used, but it is about 3 years behind gcc.  On x86_64 / BID encoding, the endian is swapped, so it doesn't work with the current gcc _DecimalXX encoding.  The gcc version of libdecnumber does works with the builtin type.  I've pulled out libdecnumber from gcc here:  https://github.com/raitechnology/libdecnumber

I'm not sure of the gcc status of _DecimalXX, since the g++ 8 distributed with FC28 no longer has _DecimalXX types unless I'm missing an cmd line option (disabled in favor of std::decimal ??).

I can merge the libgcc version into libdfp and do a pull request if that is useful.

**Comment by pmur** [comment]
I've merged the latest decNumber from GCC. I think this resolves the question.
